services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file: .env
    environment:
      SERVER_NAME: ":80"
      FRANKENPHP_CONFIG: "worker ./public/index.php"
    volumes:
      - .:/app
      - /app/vendor
      - sqlite_data:/app/var/data
    tty: true

volumes:
  sqlite_data:
